// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type BillingModel string

const (
	BillingModelPrepaid  BillingModel = "prepaid"
	BillingModelPostpaid BillingModel = "postpaid"
)

func (e *BillingModel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillingModel(s)
	case string:
		*e = BillingModel(s)
	default:
		return fmt.Errorf("unsupported scan type for BillingModel: %T", src)
	}
	return nil
}

type NullBillingModel struct {
	BillingModel BillingModel `json:"billing_model"`
	Valid        bool         `json:"valid"` // Valid is true if BillingModel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillingModel) Scan(value interface{}) error {
	if value == nil {
		ns.BillingModel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillingModel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillingModel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillingModel), nil
}

type DeploymentStatus string

const (
	DeploymentStatusActive    DeploymentStatus = "active"
	DeploymentStatusSuspended DeploymentStatus = "suspended"
	DeploymentStatusRevoked   DeploymentStatus = "revoked"
)

func (e *DeploymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeploymentStatus(s)
	case string:
		*e = DeploymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeploymentStatus: %T", src)
	}
	return nil
}

type NullDeploymentStatus struct {
	DeploymentStatus DeploymentStatus `json:"deployment_status"`
	Valid            bool             `json:"valid"` // Valid is true if DeploymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeploymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeploymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeploymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeploymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeploymentStatus), nil
}

type DeploymentType string

const (
	DeploymentTypeAws    DeploymentType = "aws"
	DeploymentTypeAzure  DeploymentType = "azure"
	DeploymentTypeGcp    DeploymentType = "gcp"
	DeploymentTypeOnprem DeploymentType = "onprem"
)

func (e *DeploymentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeploymentType(s)
	case string:
		*e = DeploymentType(s)
	default:
		return fmt.Errorf("unsupported scan type for DeploymentType: %T", src)
	}
	return nil
}

type NullDeploymentType struct {
	DeploymentType DeploymentType `json:"deployment_type"`
	Valid          bool           `json:"valid"` // Valid is true if DeploymentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeploymentType) Scan(value interface{}) error {
	if value == nil {
		ns.DeploymentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeploymentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeploymentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeploymentType), nil
}

type EndpointStatus string

const (
	EndpointStatusActive   EndpointStatus = "active"
	EndpointStatusInactive EndpointStatus = "inactive"
	EndpointStatusDeleted  EndpointStatus = "deleted"
)

func (e *EndpointStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EndpointStatus(s)
	case string:
		*e = EndpointStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EndpointStatus: %T", src)
	}
	return nil
}

type NullEndpointStatus struct {
	EndpointStatus EndpointStatus `json:"endpoint_status"`
	Valid          bool           `json:"valid"` // Valid is true if EndpointStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEndpointStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EndpointStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EndpointStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEndpointStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EndpointStatus), nil
}

type SubscriptionStatus string

const (
	SubscriptionStatusTrial     SubscriptionStatus = "trial"
	SubscriptionStatusActive    SubscriptionStatus = "active"
	SubscriptionStatusGrace     SubscriptionStatus = "grace"
	SubscriptionStatusPastDue   SubscriptionStatus = "past_due"
	SubscriptionStatusCancelled SubscriptionStatus = "cancelled"
	SubscriptionStatusExpired   SubscriptionStatus = "expired"
)

func (e *SubscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionStatus(s)
	case string:
		*e = SubscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionStatus: %T", src)
	}
	return nil
}

type NullSubscriptionStatus struct {
	SubscriptionStatus SubscriptionStatus `json:"subscription_status"`
	Valid              bool               `json:"valid"` // Valid is true if SubscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionStatus), nil
}

type TenantStatus string

const (
	TenantStatusActive    TenantStatus = "active"
	TenantStatusSuspended TenantStatus = "suspended"
	TenantStatusDeleted   TenantStatus = "deleted"
)

func (e *TenantStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantStatus(s)
	case string:
		*e = TenantStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantStatus: %T", src)
	}
	return nil
}

type NullTenantStatus struct {
	TenantStatus TenantStatus `json:"tenant_status"`
	Valid        bool         `json:"valid"` // Valid is true if TenantStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TenantStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantStatus), nil
}

type Deployment struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	DeploymentType DeploymentType     `json:"deployment_type"`
	Region         pgtype.Text        `json:"region"`
	Environment    pgtype.Text        `json:"environment"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeploymentKey  string             `json:"deployment_key"`
	Status         DeploymentStatus   `json:"status"`
}

type Endpoint struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	DeploymentID pgtype.UUID        `json:"deployment_id"`
	Hostname     pgtype.Text        `json:"hostname"`
	Os           pgtype.Text        `json:"os"`
	AgentVersion pgtype.Text        `json:"agent_version"`
	Status       EndpointStatus     `json:"status"`
	FirstSeen    pgtype.Timestamptz `json:"first_seen"`
	LastSeen     pgtype.Timestamptz `json:"last_seen"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type EntitlementEvent struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	SubscriptionID pgtype.UUID        `json:"subscription_id"`
	DeploymentID   pgtype.UUID        `json:"deployment_id"`
	EventType      string             `json:"event_type"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Feature struct {
	ID          pgtype.UUID        `json:"id"`
	FeatureCode string             `json:"feature_code"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Category    pgtype.Text        `json:"category"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Subscription struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	PlanCode     string             `json:"plan_code"`
	BillingModel BillingModel       `json:"billing_model"`
	Status       SubscriptionStatus `json:"status"`
	StartDate    pgtype.Date        `json:"start_date"`
	EndDate      pgtype.Date        `json:"end_date"`
	TrialEnd     pgtype.Date        `json:"trial_end"`
	AutoRenew    pgtype.Bool        `json:"auto_renew"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type SubscriptionFeature struct {
	SubscriptionID pgtype.UUID        `json:"subscription_id"`
	FeatureID      pgtype.UUID        `json:"feature_id"`
	Enabled        bool               `json:"enabled"`
	Limits         []byte             `json:"limits"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	ExternalRef pgtype.Text        `json:"external_ref"`
	Status      TenantStatus       `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TenantCloudAccount struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	CloudProvider  DeploymentType     `json:"cloud_provider"`
	CloudAccountID string             `json:"cloud_account_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type UsageMetricsDaily struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	UsageDate       pgtype.Date        `json:"usage_date"`
	EndpointsActive int32              `json:"endpoints_active"`
	EventsIngested  int64              `json:"events_ingested"`
	EpsAvg          int32              `json:"eps_avg"`
	EpsPeak         int32              `json:"eps_peak"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}
