// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addSubscriptionFeature = `-- name: AddSubscriptionFeature :exec

INSERT INTO subscription_features (
    subscription_id,
    feature_id,
    enabled,
    limits
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (subscription_id, feature_id)
DO UPDATE
SET enabled = EXCLUDED.enabled,
    limits = EXCLUDED.limits
`

type AddSubscriptionFeatureParams struct {
	SubscriptionID pgtype.UUID `json:"subscription_id"`
	FeatureID      pgtype.UUID `json:"feature_id"`
	Enabled        bool        `json:"enabled"`
	Limits         []byte      `json:"limits"`
}

// =========================================================
// SUBSCRIPTION FEATURE ENTITLEMENTS
// =========================================================
func (q *Queries) AddSubscriptionFeature(ctx context.Context, arg AddSubscriptionFeatureParams) error {
	_, err := q.db.Exec(ctx, addSubscriptionFeature,
		arg.SubscriptionID,
		arg.FeatureID,
		arg.Enabled,
		arg.Limits,
	)
	return err
}

const addTenantCloudAccount = `-- name: AddTenantCloudAccount :one

INSERT INTO tenant_cloud_accounts (
    tenant_id,
    cloud_provider,
    cloud_account_id
) VALUES (
    $1, $2, $3
)
RETURNING id, tenant_id, cloud_provider, cloud_account_id, created_at
`

type AddTenantCloudAccountParams struct {
	TenantID       pgtype.UUID    `json:"tenant_id"`
	CloudProvider  DeploymentType `json:"cloud_provider"`
	CloudAccountID string         `json:"cloud_account_id"`
}

// =========================================================
// CLOUD ACCOUNT MAPPINGS
// =========================================================
func (q *Queries) AddTenantCloudAccount(ctx context.Context, arg AddTenantCloudAccountParams) (TenantCloudAccount, error) {
	row := q.db.QueryRow(ctx, addTenantCloudAccount, arg.TenantID, arg.CloudProvider, arg.CloudAccountID)
	var i TenantCloudAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CloudProvider,
		&i.CloudAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const cancelSubscription = `-- name: CancelSubscription :exec
UPDATE subscriptions
SET status = 'cancelled',
    updated_at = now()
WHERE id = $1
`

func (q *Queries) CancelSubscription(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelSubscription, id)
	return err
}

const checkFeatureEnabled = `-- name: CheckFeatureEnabled :one
SELECT enabled
FROM subscription_features
WHERE subscription_id = $1
AND feature_id = $2
LIMIT 1
`

type CheckFeatureEnabledParams struct {
	SubscriptionID pgtype.UUID `json:"subscription_id"`
	FeatureID      pgtype.UUID `json:"feature_id"`
}

func (q *Queries) CheckFeatureEnabled(ctx context.Context, arg CheckFeatureEnabledParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkFeatureEnabled, arg.SubscriptionID, arg.FeatureID)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const countActiveEndpoints = `-- name: CountActiveEndpoints :one
SELECT COUNT(*)
FROM endpoints
WHERE tenant_id = $1
AND status = 'active'
`

func (q *Queries) CountActiveEndpoints(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveEndpoints, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeployment = `-- name: CreateDeployment :one

INSERT INTO deployments (
    tenant_id,
    deployment_type,
    region,
    environment
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, tenant_id, deployment_type, region, environment, created_at, updated_at, deployment_key, status
`

type CreateDeploymentParams struct {
	TenantID       pgtype.UUID    `json:"tenant_id"`
	DeploymentType DeploymentType `json:"deployment_type"`
	Region         pgtype.Text    `json:"region"`
	Environment    pgtype.Text    `json:"environment"`
}

// =========================================================
// DEPLOYMENTS
// =========================================================
func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.TenantID,
		arg.DeploymentType,
		arg.Region,
		arg.Environment,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DeploymentType,
		&i.Region,
		&i.Environment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeploymentKey,
		&i.Status,
	)
	return i, err
}

const createEntitlementEvent = `-- name: CreateEntitlementEvent :one

INSERT INTO entitlement_events (
    tenant_id,
    subscription_id,
    deployment_id,
    event_type,
    metadata
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, tenant_id, subscription_id, deployment_id, event_type, metadata, created_at
`

type CreateEntitlementEventParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	SubscriptionID pgtype.UUID `json:"subscription_id"`
	DeploymentID   pgtype.UUID `json:"deployment_id"`
	EventType      string      `json:"event_type"`
	Metadata       []byte      `json:"metadata"`
}

// =========================================================
// ENTITLEMENT EVENTS
// =========================================================
func (q *Queries) CreateEntitlementEvent(ctx context.Context, arg CreateEntitlementEventParams) (EntitlementEvent, error) {
	row := q.db.QueryRow(ctx, createEntitlementEvent,
		arg.TenantID,
		arg.SubscriptionID,
		arg.DeploymentID,
		arg.EventType,
		arg.Metadata,
	)
	var i EntitlementEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubscriptionID,
		&i.DeploymentID,
		&i.EventType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createFeature = `-- name: CreateFeature :one

INSERT INTO features (
    feature_code,
    name,
    description,
    category
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, feature_code, name, description, category, created_at
`

type CreateFeatureParams struct {
	FeatureCode string      `json:"feature_code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Category    pgtype.Text `json:"category"`
}

// =========================================================
// FEATURES
// =========================================================
func (q *Queries) CreateFeature(ctx context.Context, arg CreateFeatureParams) (Feature, error) {
	row := q.db.QueryRow(ctx, createFeature,
		arg.FeatureCode,
		arg.Name,
		arg.Description,
		arg.Category,
	)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.FeatureCode,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one

INSERT INTO subscriptions (
    tenant_id,
    plan_code,
    billing_model,
    status,
    start_date,
    end_date,
    trial_end,
    auto_renew
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
RETURNING id, tenant_id, plan_code, billing_model, status, start_date, end_date, trial_end, auto_renew, created_at, updated_at
`

type CreateSubscriptionParams struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	PlanCode     string             `json:"plan_code"`
	BillingModel BillingModel       `json:"billing_model"`
	Status       SubscriptionStatus `json:"status"`
	StartDate    pgtype.Date        `json:"start_date"`
	EndDate      pgtype.Date        `json:"end_date"`
	TrialEnd     pgtype.Date        `json:"trial_end"`
	AutoRenew    pgtype.Bool        `json:"auto_renew"`
}

// =========================================================
// SUBSCRIPTIONS
// =========================================================
func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.TenantID,
		arg.PlanCode,
		arg.BillingModel,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.TrialEnd,
		arg.AutoRenew,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlanCode,
		&i.BillingModel,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.TrialEnd,
		&i.AutoRenew,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one

INSERT INTO tenants (
    name,
    external_ref,
    status
) VALUES (
    $1, $2, $3
)
RETURNING id, name, external_ref, status, created_at, updated_at
`

type CreateTenantParams struct {
	Name        string       `json:"name"`
	ExternalRef pgtype.Text  `json:"external_ref"`
	Status      TenantStatus `json:"status"`
}

// =========================================================
// TENANTS
// =========================================================
func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.ExternalRef, arg.Status)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ExternalRef,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeployment = `-- name: DeleteDeployment :exec
DELETE FROM deployments
WHERE id = $1
`

func (q *Queries) DeleteDeployment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeployment, id)
	return err
}

const deleteEndpoint = `-- name: DeleteEndpoint :exec
DELETE FROM endpoints
WHERE id = $1
`

func (q *Queries) DeleteEndpoint(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEndpoint, id)
	return err
}

const deleteFeature = `-- name: DeleteFeature :exec
DELETE FROM features
WHERE id = $1
`

func (q *Queries) DeleteFeature(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFeature, id)
	return err
}

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenants
WHERE id = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenant, id)
	return err
}

const deleteTenantCloudAccount = `-- name: DeleteTenantCloudAccount :exec
DELETE FROM tenant_cloud_accounts
WHERE id = $1
`

func (q *Queries) DeleteTenantCloudAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenantCloudAccount, id)
	return err
}

const expireSubscriptions = `-- name: ExpireSubscriptions :execrows
UPDATE subscriptions
SET status = 'expired',
    updated_at = now()
WHERE end_date < CURRENT_DATE
AND status NOT IN ('expired','cancelled')
`

func (q *Queries) ExpireSubscriptions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireSubscriptions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, tenant_id, deployment_type, region, environment, created_at, updated_at, deployment_key, status
FROM deployments
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetDeployment(ctx context.Context, id pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DeploymentType,
		&i.Region,
		&i.Environment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeploymentKey,
		&i.Status,
	)
	return i, err
}

const getDeploymentByKey = `-- name: GetDeploymentByKey :one
SELECT id, tenant_id, status
FROM deployments
WHERE deployment_key = $1
LIMIT 1
`

type GetDeploymentByKeyRow struct {
	ID       pgtype.UUID      `json:"id"`
	TenantID pgtype.UUID      `json:"tenant_id"`
	Status   DeploymentStatus `json:"status"`
}

func (q *Queries) GetDeploymentByKey(ctx context.Context, deploymentKey string) (GetDeploymentByKeyRow, error) {
	row := q.db.QueryRow(ctx, getDeploymentByKey, deploymentKey)
	var i GetDeploymentByKeyRow
	err := row.Scan(&i.ID, &i.TenantID, &i.Status)
	return i, err
}

const getEndpoint = `-- name: GetEndpoint :one
SELECT id, tenant_id, deployment_id, hostname, os, agent_version, status, first_seen, last_seen, created_at
FROM endpoints
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetEndpoint(ctx context.Context, id pgtype.UUID) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpoint, id)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DeploymentID,
		&i.Hostname,
		&i.Os,
		&i.AgentVersion,
		&i.Status,
		&i.FirstSeen,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const getFeatureByCode = `-- name: GetFeatureByCode :one
SELECT id, feature_code, name, description, category, created_at
FROM features
WHERE feature_code = $1
LIMIT 1
`

func (q *Queries) GetFeatureByCode(ctx context.Context, featureCode string) (Feature, error) {
	row := q.db.QueryRow(ctx, getFeatureByCode, featureCode)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.FeatureCode,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, tenant_id, plan_code, billing_model, status, start_date, end_date, trial_end, auto_renew, created_at, updated_at
FROM subscriptions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSubscription(ctx context.Context, id pgtype.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlanCode,
		&i.BillingModel,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.TrialEnd,
		&i.AutoRenew,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, external_ref, status, created_at, updated_at
FROM tenants
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTenant(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ExternalRef,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantActiveSubscription = `-- name: GetTenantActiveSubscription :one
SELECT id, tenant_id, plan_code, billing_model, status, start_date, end_date, trial_end, auto_renew, created_at, updated_at
FROM subscriptions
WHERE tenant_id = $1
AND status IN ('trial','active','grace')
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetTenantActiveSubscription(ctx context.Context, tenantID pgtype.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getTenantActiveSubscription, tenantID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlanCode,
		&i.BillingModel,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.TrialEnd,
		&i.AutoRenew,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByExternalRef = `-- name: GetTenantByExternalRef :one
SELECT id, name, external_ref, status, created_at, updated_at
FROM tenants
WHERE external_ref = $1
LIMIT 1
`

func (q *Queries) GetTenantByExternalRef(ctx context.Context, externalRef pgtype.Text) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByExternalRef, externalRef)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ExternalRef,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantCloudAccount = `-- name: GetTenantCloudAccount :one
SELECT id, tenant_id, cloud_provider, cloud_account_id, created_at
FROM tenant_cloud_accounts
WHERE cloud_provider = $1
AND cloud_account_id = $2
LIMIT 1
`

type GetTenantCloudAccountParams struct {
	CloudProvider  DeploymentType `json:"cloud_provider"`
	CloudAccountID string         `json:"cloud_account_id"`
}

func (q *Queries) GetTenantCloudAccount(ctx context.Context, arg GetTenantCloudAccountParams) (TenantCloudAccount, error) {
	row := q.db.QueryRow(ctx, getTenantCloudAccount, arg.CloudProvider, arg.CloudAccountID)
	var i TenantCloudAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CloudProvider,
		&i.CloudAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const getUsageForDate = `-- name: GetUsageForDate :one
SELECT id, tenant_id, usage_date, endpoints_active, events_ingested, eps_avg, eps_peak, created_at
FROM usage_metrics_daily
WHERE tenant_id = $1
AND usage_date = $2
LIMIT 1
`

type GetUsageForDateParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	UsageDate pgtype.Date `json:"usage_date"`
}

func (q *Queries) GetUsageForDate(ctx context.Context, arg GetUsageForDateParams) (UsageMetricsDaily, error) {
	row := q.db.QueryRow(ctx, getUsageForDate, arg.TenantID, arg.UsageDate)
	var i UsageMetricsDaily
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UsageDate,
		&i.EndpointsActive,
		&i.EventsIngested,
		&i.EpsAvg,
		&i.EpsPeak,
		&i.CreatedAt,
	)
	return i, err
}

const getUsageRange = `-- name: GetUsageRange :many
SELECT id, tenant_id, usage_date, endpoints_active, events_ingested, eps_avg, eps_peak, created_at
FROM usage_metrics_daily
WHERE tenant_id = $1
AND usage_date BETWEEN $2 AND $3
ORDER BY usage_date DESC
`

type GetUsageRangeParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	UsageDate   pgtype.Date `json:"usage_date"`
	UsageDate_2 pgtype.Date `json:"usage_date_2"`
}

func (q *Queries) GetUsageRange(ctx context.Context, arg GetUsageRangeParams) ([]UsageMetricsDaily, error) {
	rows, err := q.db.Query(ctx, getUsageRange, arg.TenantID, arg.UsageDate, arg.UsageDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageMetricsDaily
	for rows.Next() {
		var i UsageMetricsDaily
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UsageDate,
			&i.EndpointsActive,
			&i.EventsIngested,
			&i.EpsAvg,
			&i.EpsPeak,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllDeployments = `-- name: ListAllDeployments :many
SELECT d.id, d.tenant_id, d.deployment_type, d.region, d.environment,
       d.deployment_key, d.status, d.created_at, d.updated_at,
       t.name AS tenant_name
FROM deployments d
JOIN tenants t ON t.id = d.tenant_id
ORDER BY d.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllDeploymentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllDeploymentsRow struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	DeploymentType DeploymentType     `json:"deployment_type"`
	Region         pgtype.Text        `json:"region"`
	Environment    pgtype.Text        `json:"environment"`
	DeploymentKey  string             `json:"deployment_key"`
	Status         DeploymentStatus   `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	TenantName     string             `json:"tenant_name"`
}

func (q *Queries) ListAllDeployments(ctx context.Context, arg ListAllDeploymentsParams) ([]ListAllDeploymentsRow, error) {
	rows, err := q.db.Query(ctx, listAllDeployments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllDeploymentsRow
	for rows.Next() {
		var i ListAllDeploymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DeploymentType,
			&i.Region,
			&i.Environment,
			&i.DeploymentKey,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByType = `-- name: ListEventsByType :many
SELECT id, tenant_id, subscription_id, deployment_id, event_type, metadata, created_at
FROM entitlement_events
WHERE event_type = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListEventsByTypeParams struct {
	EventType string `json:"event_type"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) ListEventsByType(ctx context.Context, arg ListEventsByTypeParams) ([]EntitlementEvent, error) {
	rows, err := q.db.Query(ctx, listEventsByType, arg.EventType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntitlementEvent
	for rows.Next() {
		var i EntitlementEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SubscriptionID,
			&i.DeploymentID,
			&i.EventType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatures = `-- name: ListFeatures :many
SELECT id, feature_code, name, description, category, created_at
FROM features
ORDER BY feature_code
`

func (q *Queries) ListFeatures(ctx context.Context) ([]Feature, error) {
	rows, err := q.db.Query(ctx, listFeatures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feature
	for rows.Next() {
		var i Feature
		if err := rows.Scan(
			&i.ID,
			&i.FeatureCode,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionEvents = `-- name: ListSubscriptionEvents :many
SELECT id, tenant_id, subscription_id, deployment_id, event_type, metadata, created_at
FROM entitlement_events
WHERE subscription_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSubscriptionEvents(ctx context.Context, subscriptionID pgtype.UUID) ([]EntitlementEvent, error) {
	rows, err := q.db.Query(ctx, listSubscriptionEvents, subscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntitlementEvent
	for rows.Next() {
		var i EntitlementEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SubscriptionID,
			&i.DeploymentID,
			&i.EventType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionFeatures = `-- name: ListSubscriptionFeatures :many
SELECT
    sf.subscription_id, sf.feature_id, sf.enabled, sf.limits, sf.created_at,
    f.feature_code,
    f.name
FROM subscription_features sf
JOIN features f ON f.id = sf.feature_id
WHERE sf.subscription_id = $1
`

type ListSubscriptionFeaturesRow struct {
	SubscriptionID pgtype.UUID        `json:"subscription_id"`
	FeatureID      pgtype.UUID        `json:"feature_id"`
	Enabled        bool               `json:"enabled"`
	Limits         []byte             `json:"limits"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	FeatureCode    string             `json:"feature_code"`
	Name           string             `json:"name"`
}

func (q *Queries) ListSubscriptionFeatures(ctx context.Context, subscriptionID pgtype.UUID) ([]ListSubscriptionFeaturesRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionFeatures, subscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscriptionFeaturesRow
	for rows.Next() {
		var i ListSubscriptionFeaturesRow
		if err := rows.Scan(
			&i.SubscriptionID,
			&i.FeatureID,
			&i.Enabled,
			&i.Limits,
			&i.CreatedAt,
			&i.FeatureCode,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantCloudAccounts = `-- name: ListTenantCloudAccounts :many
SELECT id, tenant_id, cloud_provider, cloud_account_id, created_at
FROM tenant_cloud_accounts
WHERE tenant_id = $1
`

func (q *Queries) ListTenantCloudAccounts(ctx context.Context, tenantID pgtype.UUID) ([]TenantCloudAccount, error) {
	rows, err := q.db.Query(ctx, listTenantCloudAccounts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TenantCloudAccount
	for rows.Next() {
		var i TenantCloudAccount
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CloudProvider,
			&i.CloudAccountID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantDeployments = `-- name: ListTenantDeployments :many
SELECT id, tenant_id, deployment_type, region, environment, created_at, updated_at, deployment_key, status
FROM deployments
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTenantDeployments(ctx context.Context, tenantID pgtype.UUID) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listTenantDeployments, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DeploymentType,
			&i.Region,
			&i.Environment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeploymentKey,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantEndpoints = `-- name: ListTenantEndpoints :many
SELECT id, tenant_id, deployment_id, hostname, os, agent_version, status, first_seen, last_seen, created_at
FROM endpoints
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTenantEndpoints(ctx context.Context, tenantID pgtype.UUID) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, listTenantEndpoints, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Endpoint
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DeploymentID,
			&i.Hostname,
			&i.Os,
			&i.AgentVersion,
			&i.Status,
			&i.FirstSeen,
			&i.LastSeen,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantEvents = `-- name: ListTenantEvents :many
SELECT id, tenant_id, subscription_id, deployment_id, event_type, metadata, created_at
FROM entitlement_events
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTenantEventsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListTenantEvents(ctx context.Context, arg ListTenantEventsParams) ([]EntitlementEvent, error) {
	rows, err := q.db.Query(ctx, listTenantEvents, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntitlementEvent
	for rows.Next() {
		var i EntitlementEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SubscriptionID,
			&i.DeploymentID,
			&i.EventType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantSubscriptions = `-- name: ListTenantSubscriptions :many
SELECT id, tenant_id, plan_code, billing_model, status, start_date, end_date, trial_end, auto_renew, created_at, updated_at
FROM subscriptions
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTenantSubscriptions(ctx context.Context, tenantID pgtype.UUID) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listTenantSubscriptions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PlanCode,
			&i.BillingModel,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.TrialEnd,
			&i.AutoRenew,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, external_ref, status, created_at, updated_at
FROM tenants
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTenantsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ExternalRef,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerEndpoint = `-- name: RegisterEndpoint :one

INSERT INTO endpoints (
    tenant_id,
    deployment_id,
    hostname,
    os,
    agent_version
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, tenant_id, deployment_id, hostname, os, agent_version, status, first_seen, last_seen, created_at
`

type RegisterEndpointParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	DeploymentID pgtype.UUID `json:"deployment_id"`
	Hostname     pgtype.Text `json:"hostname"`
	Os           pgtype.Text `json:"os"`
	AgentVersion pgtype.Text `json:"agent_version"`
}

// =========================================================
// ENDPOINTS / AGENTS
// =========================================================
func (q *Queries) RegisterEndpoint(ctx context.Context, arg RegisterEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, registerEndpoint,
		arg.TenantID,
		arg.DeploymentID,
		arg.Hostname,
		arg.Os,
		arg.AgentVersion,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DeploymentID,
		&i.Hostname,
		&i.Os,
		&i.AgentVersion,
		&i.Status,
		&i.FirstSeen,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const removeSubscriptionFeature = `-- name: RemoveSubscriptionFeature :exec
DELETE FROM subscription_features
WHERE subscription_id = $1
AND feature_id = $2
`

type RemoveSubscriptionFeatureParams struct {
	SubscriptionID pgtype.UUID `json:"subscription_id"`
	FeatureID      pgtype.UUID `json:"feature_id"`
}

func (q *Queries) RemoveSubscriptionFeature(ctx context.Context, arg RemoveSubscriptionFeatureParams) error {
	_, err := q.db.Exec(ctx, removeSubscriptionFeature, arg.SubscriptionID, arg.FeatureID)
	return err
}

const searchEventsByMetadata = `-- name: SearchEventsByMetadata :many
SELECT id, tenant_id, subscription_id, deployment_id, event_type, metadata, created_at
FROM entitlement_events
WHERE metadata @> $1
ORDER BY created_at DESC
LIMIT $2
`

type SearchEventsByMetadataParams struct {
	Metadata []byte `json:"metadata"`
	Limit    int32  `json:"limit"`
}

func (q *Queries) SearchEventsByMetadata(ctx context.Context, arg SearchEventsByMetadataParams) ([]EntitlementEvent, error) {
	rows, err := q.db.Query(ctx, searchEventsByMetadata, arg.Metadata, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntitlementEvent
	for rows.Next() {
		var i EntitlementEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SubscriptionID,
			&i.DeploymentID,
			&i.EventType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
UPDATE deployments
SET status = $2,
    updated_at = now()
WHERE id = $1
`

type UpdateDeploymentStatusParams struct {
	ID     pgtype.UUID      `json:"id"`
	Status DeploymentStatus `json:"status"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.db.Exec(ctx, updateDeploymentStatus, arg.ID, arg.Status)
	return err
}

const updateEndpointHeartbeat = `-- name: UpdateEndpointHeartbeat :exec
UPDATE endpoints
SET last_seen = now()
WHERE id = $1
`

func (q *Queries) UpdateEndpointHeartbeat(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateEndpointHeartbeat, id)
	return err
}

const updateEndpointStatus = `-- name: UpdateEndpointStatus :exec
UPDATE endpoints
SET status = $2
WHERE id = $1
`

type UpdateEndpointStatusParams struct {
	ID     pgtype.UUID    `json:"id"`
	Status EndpointStatus `json:"status"`
}

func (q *Queries) UpdateEndpointStatus(ctx context.Context, arg UpdateEndpointStatusParams) error {
	_, err := q.db.Exec(ctx, updateEndpointStatus, arg.ID, arg.Status)
	return err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :exec
UPDATE subscriptions
SET status = $2,
    updated_at = now()
WHERE id = $1
`

type UpdateSubscriptionStatusParams struct {
	ID     pgtype.UUID        `json:"id"`
	Status SubscriptionStatus `json:"status"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionStatus, arg.ID, arg.Status)
	return err
}

const updateTenantStatus = `-- name: UpdateTenantStatus :exec
UPDATE tenants
SET status = $2,
    updated_at = now()
WHERE id = $1
`

type UpdateTenantStatusParams struct {
	ID     pgtype.UUID  `json:"id"`
	Status TenantStatus `json:"status"`
}

func (q *Queries) UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) error {
	_, err := q.db.Exec(ctx, updateTenantStatus, arg.ID, arg.Status)
	return err
}

const upsertUsageMetricsDaily = `-- name: UpsertUsageMetricsDaily :exec

INSERT INTO usage_metrics_daily (
    tenant_id,
    usage_date,
    endpoints_active,
    events_ingested,
    eps_avg,
    eps_peak
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (tenant_id, usage_date)
DO UPDATE
SET endpoints_active = EXCLUDED.endpoints_active,
    events_ingested = EXCLUDED.events_ingested,
    eps_avg = EXCLUDED.eps_avg,
    eps_peak = EXCLUDED.eps_peak
`

type UpsertUsageMetricsDailyParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	UsageDate       pgtype.Date `json:"usage_date"`
	EndpointsActive int32       `json:"endpoints_active"`
	EventsIngested  int64       `json:"events_ingested"`
	EpsAvg          int32       `json:"eps_avg"`
	EpsPeak         int32       `json:"eps_peak"`
}

// =========================================================
// USAGE METRICS
// =========================================================
func (q *Queries) UpsertUsageMetricsDaily(ctx context.Context, arg UpsertUsageMetricsDailyParams) error {
	_, err := q.db.Exec(ctx, upsertUsageMetricsDaily,
		arg.TenantID,
		arg.UsageDate,
		arg.EndpointsActive,
		arg.EventsIngested,
		arg.EpsAvg,
		arg.EpsPeak,
	)
	return err
}
