// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// =========================================================
	// SUBSCRIPTION FEATURE ENTITLEMENTS
	// =========================================================
	AddSubscriptionFeature(ctx context.Context, arg AddSubscriptionFeatureParams) error
	// =========================================================
	// CLOUD ACCOUNT MAPPINGS
	// =========================================================
	AddTenantCloudAccount(ctx context.Context, arg AddTenantCloudAccountParams) (TenantCloudAccount, error)
	CancelSubscription(ctx context.Context, id pgtype.UUID) error
	CheckFeatureEnabled(ctx context.Context, arg CheckFeatureEnabledParams) (bool, error)
	CountActiveEndpoints(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	// =========================================================
	// DEPLOYMENTS
	// =========================================================
	CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error)
	// =========================================================
	// ENTITLEMENT EVENTS
	// =========================================================
	CreateEntitlementEvent(ctx context.Context, arg CreateEntitlementEventParams) (EntitlementEvent, error)
	// =========================================================
	// FEATURES
	// =========================================================
	CreateFeature(ctx context.Context, arg CreateFeatureParams) (Feature, error)
	// =========================================================
	// SUBSCRIPTIONS
	// =========================================================
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	// =========================================================
	// TENANTS
	// =========================================================
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	DeleteDeployment(ctx context.Context, id pgtype.UUID) error
	DeleteEndpoint(ctx context.Context, id pgtype.UUID) error
	DeleteFeature(ctx context.Context, id pgtype.UUID) error
	DeleteTenant(ctx context.Context, id pgtype.UUID) error
	DeleteTenantCloudAccount(ctx context.Context, id pgtype.UUID) error
	ExpireSubscriptions(ctx context.Context) (int64, error)
	GetDeployment(ctx context.Context, id pgtype.UUID) (Deployment, error)
	GetDeploymentByKey(ctx context.Context, deploymentKey string) (GetDeploymentByKeyRow, error)
	GetEndpoint(ctx context.Context, id pgtype.UUID) (Endpoint, error)
	GetFeatureByCode(ctx context.Context, featureCode string) (Feature, error)
	GetSubscription(ctx context.Context, id pgtype.UUID) (Subscription, error)
	GetTenant(ctx context.Context, id pgtype.UUID) (Tenant, error)
	GetTenantActiveSubscription(ctx context.Context, tenantID pgtype.UUID) (Subscription, error)
	GetTenantByExternalRef(ctx context.Context, externalRef pgtype.Text) (Tenant, error)
	GetTenantCloudAccount(ctx context.Context, arg GetTenantCloudAccountParams) (TenantCloudAccount, error)
	GetUsageForDate(ctx context.Context, arg GetUsageForDateParams) (UsageMetricsDaily, error)
	GetUsageRange(ctx context.Context, arg GetUsageRangeParams) ([]UsageMetricsDaily, error)
	ListAllDeployments(ctx context.Context, arg ListAllDeploymentsParams) ([]ListAllDeploymentsRow, error)
	ListEventsByType(ctx context.Context, arg ListEventsByTypeParams) ([]EntitlementEvent, error)
	ListFeatures(ctx context.Context) ([]Feature, error)
	ListSubscriptionEvents(ctx context.Context, subscriptionID pgtype.UUID) ([]EntitlementEvent, error)
	ListSubscriptionFeatures(ctx context.Context, subscriptionID pgtype.UUID) ([]ListSubscriptionFeaturesRow, error)
	ListTenantCloudAccounts(ctx context.Context, tenantID pgtype.UUID) ([]TenantCloudAccount, error)
	ListTenantDeployments(ctx context.Context, tenantID pgtype.UUID) ([]Deployment, error)
	ListTenantEndpoints(ctx context.Context, tenantID pgtype.UUID) ([]Endpoint, error)
	ListTenantEvents(ctx context.Context, arg ListTenantEventsParams) ([]EntitlementEvent, error)
	ListTenantSubscriptions(ctx context.Context, tenantID pgtype.UUID) ([]Subscription, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error)
	// =========================================================
	// ENDPOINTS / AGENTS
	// =========================================================
	RegisterEndpoint(ctx context.Context, arg RegisterEndpointParams) (Endpoint, error)
	RemoveSubscriptionFeature(ctx context.Context, arg RemoveSubscriptionFeatureParams) error
	SearchEventsByMetadata(ctx context.Context, arg SearchEventsByMetadataParams) ([]EntitlementEvent, error)
	UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error
	UpdateEndpointHeartbeat(ctx context.Context, id pgtype.UUID) error
	UpdateEndpointStatus(ctx context.Context, arg UpdateEndpointStatusParams) error
	UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error
	UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) error
	// =========================================================
	// USAGE METRICS
	// =========================================================
	UpsertUsageMetricsDaily(ctx context.Context, arg UpsertUsageMetricsDailyParams) error
}

var _ Querier = (*Queries)(nil)
